CREATE TABLE dishes (
  id INTEGER NOT NULL PRIMARY KEY,
  name_en VARCHAR NOT NULL,
  name_cn VARCHAR NOT NULL,
  menu_type VARCHAR NOT NULL,
  price FLOAT NOT NULL,
  is_set_meal BOOLEAN NOT NULL DEFAULT 0,
  is_attached BOOLEAN NOT NULL DEFAULT 0,
  is_selectable BOOLEAN NOT NULL DEFAULT 0,
  notes TEXT NULL
);

INSERT INTO dishes (name_en, name_cn, menu_type, price, is_set_meal, is_attached, is_selectable, notes) VALUES
('Mixed Appetiser', '拼盘', 'Starters', 6.5, FALSE, FALSE, FALSE, NULL),
('Mongolian Aromatic Crispy Lamb', '香羊', 'Starters', 8.5, FALSE, FALSE, FALSE, NULL),
('1/4 Aromatic Crispy Duck', '1/4香酥鸭', 'Starters', 8.5, FALSE, FALSE, FALSE, NULL),
('1/2 Aromatic Crispy Duck', '1/2香酥鸭', 'Starters', 16, FALSE, FALSE, FALSE, NULL),
('Prawn on Toast with Sesame Seed', '芝虾', 'Starters', 4, FALSE, FALSE, FALSE, NULL),
('Mini Panacake Roll (10)', '小卷(10)', 'Starters', 3, FALSE, FALSE, FALSE, NULL),
('Cantonese Roll (5)', '粤卷(5)', 'Starters', 3, FALSE, FALSE, FALSE, NULL),
('Deep Fried Crispy Won Ton', '炸云吞', 'Starters', 4, FALSE, FALSE, FALSE, NULL),
('Spring Roll (2)', '春卷(2)', 'Starters', 2, FALSE, FALSE, FALSE, NULL),
('Chicken & Sweet Corn Soup', '鸡米汤', 'Soup Ribs', 2.2, FALSE, FALSE, FALSE, NULL),
('Crab Meat & Sweet Corn Soup', '蟹米汤', 'Soup Ribs', 2.2, FALSE, FALSE, FALSE, NULL),
('Chicken & Mushroom Soup', '毛鸡汤', 'Soup Ribs', 2.2, FALSE, FALSE, FALSE, NULL),
('Chicken & Noodle Soup', '鸡面汤', 'Soup Ribs', 2.2, FALSE, FALSE, FALSE, NULL),
('Peking Hot & Sour Soup', '酸辣汤', 'Soup Ribs', 2.2, FALSE, FALSE, FALSE, NULL),
('BBQ Spare Ribs', 'BBQ 骨', 'Soup Ribs', 5.2, FALSE, FALSE, FALSE, NULL),
('Spare Ribs in Plum Sauce', '梅子骨', 'Soup Ribs', 5.2, FALSE, FALSE, FALSE, NULL),
('Spare Ribs with Lemon', '柠檬骨', 'Soup Ribs', 5.2, FALSE, FALSE, FALSE, NULL),
('Spare Ribs in Sweet & Sour Sauce', '古骨', 'Soup Ribs', 5.2, FALSE, FALSE, FALSE, NULL),
('Spare Ribs in Peking Sauce', '京汁', 'Soup Ribs', 5.2, FALSE, FALSE, FALSE, NULL),
('Salt & Pepper Spare Ribs', '召盐骨', 'Soup Ribs', 5.2, FALSE, FALSE, FALSE, NULL),
('Deep Fried Salt & Pepper Chicken Wings', '召盐鸡翅', 'C Wings', 5, FALSE, FALSE, FALSE, NULL),
('Deep Fried Chicken Wings in Peking Sauce', '京汁鸡翅', 'C Wings', 5, FALSE, FALSE, FALSE, NULL),
('Chicken Wings in SSS', '古鸡翅', 'C Wings', 5, FALSE, FALSE, FALSE, NULL),
('Deep Fried Chicken Wings in Satay Sauce', '沙爹鸡翅', 'C Wings', 5, FALSE, FALSE, FALSE, NULL),
('Deep Fried Chicken Wings in Szechuan Sauce', '四川鸡翅', 'C Wings', 5, FALSE, FALSE, FALSE, NULL),
('Deep Fried Chicken Wings in Kung Po Sauce', '宫保鸡翅', 'C Wings', 5, FALSE, FALSE, FALSE, NULL),
('Fried Squid with Ginger & Spring Onion', '姜葱尤', 'Seafood', 6, FALSE, TRUE, TRUE, '300,301,302,303'),
('Fried Squid with Chilli & Black Bean Sauce', '士汁尤', 'Seafood', 6, FALSE, TRUE, TRUE, '300,301,302,303'),
('Deep Fried Salt & Pepper Squid', '召盐尤', 'Seafood', 6, FALSE, TRUE, TRUE, '300,301,302,303'),
('Fried Mussel with Chilli & Black Bean Sauce', '士汁青口', 'Seafood', 5.8, FALSE, TRUE, TRUE, '300,301,302,303'),
('Fried Mussel with Ginger & Spring Onion', '姜葱青口', 'Seafood', 5.8, FALSE, TRUE, TRUE, '300,301,302,303'),
('Fried Scallop with Ginger & Spring Onion', '姜葱带子', 'Seafood', 6.8, FALSE, TRUE, TRUE, '300,301,302,303'),
('Fried Scallop with Chilli & Black Bean Sauce', '豉汁带子', 'Seafood', 6.8, FALSE, TRUE, TRUE, '300,301,302,303'),
('King Prawn & Chicken GP in B B Sauce', '士召虾鸡', 'B.Bean S', 6, FALSE, TRUE, TRUE, '300,301,302,303'),
('King Prawn Chicken & Mushroom in B B Sauce', '士汁毛虾鸡', 'B.Bean S', 6, FALSE, TRUE, TRUE, '300,301,302,303'),
('King Prawn GP in B B Sauce', '士召虾', 'B.Bean S', 6, FALSE, TRUE, TRUE, '300,301,302,303'),
('King Prawn Mushroom in B B Sauce', '士汁毛虾', 'B.Bean S', 6, FALSE, TRUE, TRUE, '300,301,302,303'),
('Chicken GP in B B Sauce', '士召鸡', 'B.Bean S', 5.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Chicken Mushroom in B B Sauce', '士汁毛鸡', 'B.Bean S', 5.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Beef GP in B B Sauce', '士召牛', 'B.Bean S', 5.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Beef Mushroom in B B Sauce', '士汁毛牛', 'B.Bean S', 5.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Roast Pork GP in B B Sauce', '士召叉烧', 'B.Bean S', 5.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Roast Pork Mushroom in B B Sauce', '士汁毛叉烧', 'B.Bean S', 5.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('King Prawn & Chicken in Cantonese Style', '粤汁虾鸡', 'Cant. Szech', 6, FALSE, TRUE, TRUE, '300,301,302,303'),
('King Prawn in Cantonese Style', '粤汁虾', 'Cant. Szech', 6, FALSE, TRUE, TRUE, '300,301,302,303'),
('Chicken in Cantonese Style', '粤汁鸡', 'Cant. Szech', 5.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Beef in Cantonese Style', '粤汁牛', 'Cant. Szech', 5.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Roast Pork in Cantonese Style', '粤汁叉烧', 'Cant. Szech', 5.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Roast Duck in Orange Sauce', '橙汁鸭', 'Roast Duck', 6.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Roast Duck with Mushroom', '毛菇鸭', 'Roast Duck', 6.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Roast Duck in Plum Sauce', '梅子鸭', 'Roast Duck', 6.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Roast Duck in Chinese Style', '中鸭', 'Roast Duck', 6.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Roast Duck with Pineapple', '菠萝鸭', 'Roast Duck', 6.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Roast Duck with Cashewnuts', '腰果鸭', 'Roast Duck', 6.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Roast Duck in Oyster Sauce', '蚝油鸭', 'Roast Duck', 6.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Roast Duck with Bamboo Shoots & Water Chestnuts', '竹马鸭', 'Roast Duck', 6.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Roast Duck with Mixed Vegetables', '什才鸭', 'Roast Duck', 6.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Kung Po House Special with Cashew Nuts', '招牌宫保腰', 'Kung Po Satay', 6, FALSE, TRUE, TRUE, '300,301,302,303'),
('Kung Po King Prawn & Chicken with Cashew Nuts', '宫保腰虾鸡', 'Kung Po Satay', 6, FALSE, TRUE, TRUE, '300,301,302,303'),
('Kung Po King Prawn with Cashew Nuts', '宫保腰虾', 'Kung Po Satay', 6, FALSE, TRUE, TRUE, '300,301,302,303'),
('Kung Po Chicken with Cashew Nuts', '宫保腰鸡', 'Kung Po Satay', 5.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Kung Po Beef with Cashew Nuts', '宫保腰牛', 'Kung Po Satay', 5.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('Kung Po Roast Pork with Cashew Nuts', '宫保腰叉', 'Kung Po Satay', 5.5, FALSE, TRUE, TRUE, '300,301,302,303'),
('House Special Fried Rice', '招牌饭', 'Fried Rice', 6, FALSE, FALSE, FALSE, NULL),
('King Prawn & Chicken Fried Rice', '虾鸡饭', 'Fried Rice', 6, FALSE, FALSE, FALSE, NULL),
('King Prawn Fried Rice', '大虾饭', 'Fried Rice', 6, FALSE, FALSE, FALSE, NULL),
('Yung Chow Fried Rice', '扬州炒饭', 'Fried Rice', 5.8, FALSE, FALSE, FALSE, NULL),
('Singapore Style Fried Rice', '星饭', 'Fried Rice', 5.8, FALSE, FALSE, FALSE, NULL),
('Shrimp Fried Rice', '虾仔饭', 'Fried Rice', 5.5, FALSE, FALSE, FALSE, NULL),
('Chicken Fried Rice', '鸡饭', 'Fried Rice', 5.2, FALSE, FALSE, FALSE, NULL),
('Beef Fried Rice', '牛饭', 'Fried Rice', 5.2, FALSE, FALSE, FALSE, NULL),
('Roast Pork Fried Rice', '叉烧饭', 'Fried Rice', 5.2, FALSE, FALSE, FALSE, NULL),
('Special Roast Duck Fried Rice', '鸭饭', 'Fried Rice', 6.7, FALSE, FALSE, FALSE, NULL),
('Special Roast Duck & Chicken Fried Rice', '鸭鸡饭', 'Fried Rice', 6.7, FALSE, FALSE, FALSE, NULL),
('Special Roast Duck & Roast Pork Fried Rice', '叉鸭饭', 'Fried Rice', 6.7, FALSE, FALSE, FALSE, NULL),
('Mushroom Fried Rice', '毛菇饭', 'Fried Rice', 4.7, FALSE, FALSE, FALSE, NULL),
('House Special Chow Mein', '招牌面', 'Chow Mein', 6, FALSE, FALSE, FALSE, NULL),
('King Prawn & Chicken Chow Mein', '虾鸡面', 'Chow Mein', 6, FALSE, FALSE, FALSE, NULL),
('King Prawn Chow Mein', '大虾面', 'Chow Mein', 6, FALSE, FALSE, FALSE, NULL),
('Singapore Style Chow Mein', '星面', 'Chow Mein', 5.8, FALSE, FALSE, FALSE, NULL),
('Yung Chow Mein', '扬州面', 'Chow Mein', 5.8, FALSE, FALSE, FALSE, NULL),
('Malaysian Style Chow Mein', '马来面', 'Chow Mein', 5.8, FALSE, FALSE, FALSE, NULL),
('Chicken Chow Mein', '鸡面', 'Chow Mein', 5.2, FALSE, FALSE, FALSE, NULL),
('Beef Chow Mein', '牛面', 'Chow Mein', 5.2, FALSE, FALSE, FALSE, NULL),
('Shrimp Chow Mein', '虾仔面', 'Chow Mein', 5.2, FALSE, FALSE, FALSE, NULL),
('Roast Pork Chow Mein', '叉烧面', 'Chow Mein', 5.2, FALSE, FALSE, FALSE, NULL),
('Mixed Vegetables Chow Mein', '什才面', 'Chow Mein', 4.7, FALSE, FALSE, FALSE, NULL),
('Mushroom Chow Mein', '毛菇面', 'Chow Mein', 4.7, FALSE, FALSE, FALSE, NULL),
('Special Roast Duck Chow Mein', '鸭面', 'Chow Mein', 6.7, FALSE, FALSE, FALSE, NULL),
('Special Roast Duck & Chicken Chow Mein', '鸭鸡面', 'Chow Mein', 6.7, FALSE, FALSE, FALSE, NULL),
('Special Roast Duck & Roast Pork Chow Mein', '叉鸭面', 'Chow Mein', 6.7, FALSE, FALSE, FALSE, NULL),
('Mix meat chow mein BB source', '什面 BB酱', 'Chow Mein', 6.5, FALSE, FALSE, FALSE, NULL),
('House Special with Mushroom in Plum Sauce', '招牌梅子毛', 'Plum Ginger', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn Chow Mein BBS', '黑椒大虾炒面', 'Chow Mein', 6.5, FALSE, FALSE, FALSE, NULL),
('King Prawn & Chicken with Mushroom in Plum Sauce', '梅子毛虾鸡', 'Plum Ginger', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with Mushroom in Plum Sauce', '梅子毛虾', 'Plum Ginger', 6, FALSE, TRUE, TRUE, NULL),
('Chicken with Mushroom in Plum Sauce', '梅子毛鸡', 'Plum Ginger', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with Mushroom in Plum Sauce', '梅子毛牛', 'Plum Ginger', 5.5, FALSE, TRUE, TRUE, NULL),
('Shrimp with Mushroom in Plum Sauce', '梅子毛虾仔', 'Plum Ginger', 5.5, FALSE, TRUE, TRUE, NULL),
('Roast Pork with Mushroom in Plum Sauce', '梅子毛叉', 'Plum Ginger', 5.5, FALSE, TRUE, TRUE, NULL),
('House Special with Ginger & Spring Onion', '招牌姜葱', 'Plum Ginger', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn & Chicken with Ginger & Spring Onion', '姜葱虾鸡', 'Plum Ginger', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with Ginger & Spring Onion', '姜葱大虾', 'Plum Ginger', 6, FALSE, TRUE, TRUE, NULL),
('Chicken with Ginger & Spring Onion', '姜葱鸡', 'Plum Ginger', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with Ginger & Spring Onion', '姜葱牛', 'Plum Ginger', 5.5, FALSE, TRUE, TRUE, NULL),
('Roast Pork with Ginger & Spring Onion', '姜葱叉', 'Plum Ginger', 5.5, FALSE, TRUE, TRUE, NULL),
('King Prawn in OK Sauce', 'OK汁大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn in Thai Style', '泰大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with Mushroom', '毛菇大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with Tomato', '番茄大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with Pineapple', '菠萝大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with Cashew Nuts', '腰果大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with Sweet Corn', '栗米大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with Bean Sprouts', '芽菜大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with Mixed Vegetables', '什才大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn in Oyster Sauce', '蚝油大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn in Peking Sauce', '京汁大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('Salt & Pepper King Prawn', '召盐大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn in Garlic Cream Sauce', '蒜大虾', 'King Prawn', 6, FALSE, TRUE, TRUE, NULL),
('Deep Fried Chicken in Lemon Sauce', '柠檬鸡', 'Chicken', 6, FALSE, TRUE, TRUE, NULL),
('Deep Fried Chicken in Orange Sauce', '橙汁鸡', 'Chicken', 6, FALSE, TRUE, TRUE, NULL),
('Deep Fried Chicken in Garlic Cream Sauce', '蒜鸡', 'Chicken', 6, FALSE, TRUE, TRUE, NULL),
('Chicken in OK Sauce', 'OK鸡', 'Chicken', 5.5, FALSE, TRUE, TRUE, NULL),
('Chicken in Thai Style', '泰鸡', 'Chicken', 5.5, FALSE, TRUE, TRUE, NULL),
('Chicken with Mushroom', '毛菇鸡', 'Chicken', 5.5, FALSE, TRUE, TRUE, NULL),
('Chicken with Tomato', '番茄鸡', 'Chicken', 5.5, FALSE, TRUE, TRUE, NULL),
('Chicken with Pineapple', '菠萝鸡', 'Chicken', 5.5, FALSE, TRUE, TRUE, NULL),
('Chicken with Cashew Nuts', '腰果鸡', 'Chicken', 5.5, FALSE, TRUE, TRUE, NULL),
('Chicken with Sweet Corn', '栗米鸡', 'Chicken', 5.5, FALSE, TRUE, TRUE, NULL),
('Chicken in Chinese Style', '中鸡', 'Chicken', 5.5, FALSE, TRUE, TRUE, NULL),
('Chicken with Mixed Vegetables', '什才鸡', 'Chicken', 5.5, FALSE, TRUE, TRUE, NULL),
('Chicken with Bamboo Shoots & Water Chestnuts', '竹马鸡', 'Chicken', 5.5, FALSE, TRUE, TRUE, NULL),
('Chicken in Oyster Sauce', '蚝油鸡', 'Chicken', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef in OK Sauce', 'OK牛', 'Beef', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef in Thai Style', '泰牛', 'Beef', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with Mushroom', '毛菇牛', 'Beef', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with Tomato', '番茄牛', 'Beef', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with Pineapple', '菠萝牛', 'Beef', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with Cashew Nuts', '腰果牛', 'Beef', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with Sweet Corn', '栗米牛', 'Beef', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with Bean Sprouts', '芽菜牛', 'Beef', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with Mixed Vegetables', '什才牛', 'Beef', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with Bamboo Shoots & Water Chestnuts', '竹马牛', 'Beef', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with Onion', '洋葱牛', 'Beef', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with Oyster Sauce', '蚝油牛', 'Beef', 5.5, FALSE, TRUE, TRUE, NULL),
('House Special Curry', '招牌咖喱', 'Curry', 6, FALSE, TRUE, TRUE, NULL),
('Roast Duck Curry', '咖喱鸭', 'Curry', 6.5, FALSE, TRUE, TRUE, NULL),
('King Prawn & Chicken Curry', '咖喱虾鸡', 'Curry', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn Curry', '咖喱大虾', 'Curry', 6, FALSE, TRUE, TRUE, NULL),
('Chicken Curry', '咖喱鸡', 'Curry', 5.4, FALSE, TRUE, TRUE, NULL),
('Beef Curry', '咖喱牛', 'Curry', 5.4, FALSE, TRUE, TRUE, NULL),
('Roast Pork Curry', '咖喱叉', 'Curry', 5.4, FALSE, TRUE, TRUE, NULL),
('Shrimp Curry', '咖喱虾仔', 'Curry', 5.4, FALSE, TRUE, TRUE, NULL),
('King Prawn & Chicken with Mushroom Curry', '咖喱毛虾鸡', 'Curry', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with Mushroom Curry', '咖喱毛虾', 'Curry', 6, FALSE, TRUE, TRUE, NULL),
('Chicken with Mushroom Curry', '咖喱毛菇鸡', 'Curry', 5.7, FALSE, TRUE, TRUE, NULL),
('Beef with Mushroom Curry', '咖喱毛菇牛', 'Curry', 5.7, FALSE, TRUE, TRUE, NULL),
('Roast Pork with Mushroom Curry', '咖喱毛叉烧', 'Curry', 5.7, FALSE, TRUE, TRUE, NULL),
('Mushroom Curry', '咖喱毛菇', 'Curry', 4.7, FALSE, TRUE, TRUE, NULL),
('King Prawn & Chicken with GP Curry', '咖喱鸡虾召', 'Curry', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with GP Curry', '咖喱大虾召', 'Curry', 6, FALSE, TRUE, TRUE, NULL),
('Chicken with GP Curry', '咖喱鸡召', 'Curry', 5.7, FALSE, TRUE, TRUE, NULL),
('Beef with GP Curry', '咖喱牛召', 'Curry', 5.7, FALSE, TRUE, TRUE, NULL),
('Mixed Vegetables Curry', '咖喱什才', 'Curry', 4.7, FALSE, TRUE, TRUE, NULL),
('House Special in Satay Sauce', '招牌沙爹', 'Kung Po Satay', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn & Chicken in Satay Sauce', '沙爹虾鸡', 'Kung Po Satay', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn & Beef in Satay Sauce', '沙爹虾牛', 'Kung Po Satay', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn in Satay Sauce', '沙爹虾', 'Kung Po Satay', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn & Roast Pork in Satay Sauce', '沙爹叉虾', 'Kung Po Satay', 6, FALSE, TRUE, TRUE, NULL),
('Chicken in Satay Sauce', '沙爹鸡翅', 'Kung Po Satay', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef in Satay Sauce', '沙爹牛', 'Kung Po Satay', 5.5, FALSE, TRUE, TRUE, NULL),
('Roast Pork in Satay Sauce', '沙爹叉', 'Kung Po Satay', 5.5, FALSE, TRUE, TRUE, NULL),
('House Special in Szechuan Sauce', '招牌四川', 'Cant. Szech', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn & Chicken in Szechuan Sauce', '四川虾鸡', 'Cant. Szech', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn & Beef in Szechuan Sauce', '四川虾牛', 'Cant. Szech', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn & Roast Pork in Szechuan Sauce', '四川叉虾', 'Cant. Szech', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn in Szechuan Sauce', '四川虾', 'Cant. Szech', 6, FALSE, TRUE, TRUE, NULL),
('Chicken in Szechuan Sauce', '四川鸡', 'Cant. Szech', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef in Szechuan Sauce', '四川牛', 'Cant. Szech', 5.5, FALSE, TRUE, TRUE, NULL),
('Roast Pork in Szechuan Sauce', '四川叉', 'Cant. Szech', 5.5, FALSE, TRUE, TRUE, NULL),
('Mixed Veg in Satay Sauce', '沙嗲什菜', 'Veg', 4.7, FALSE, TRUE, TRUE, NULL),
('Mixed Veg in Kung Po Sauce', '宫保什菜', 'Veg', 4.7, FALSE, TRUE, TRUE, NULL),
('Mixed Veg in Cantonese Sauce', '广汁什菜', 'Veg', 4.7, FALSE, TRUE, TRUE, NULL),
('Mixed Veg in Thai Sauce', '泰汁什菜', 'Veg', 4.7, FALSE, TRUE, TRUE, NULL),
('Mixed Veg in OK Sauce', 'OK汁什菜', 'Veg', 4.7, FALSE, TRUE, TRUE, NULL),
('Mixed Veg in Szechuan Sauce', '四川什菜', 'Veg', 4.7, FALSE, TRUE, TRUE, NULL),
('Mixed Veg in Black Bean Sauce', '黑椒什菜', 'Veg', 4.7, FALSE, TRUE, TRUE, NULL),
('Mixed Veg in Plum Sauce', '梅汁什菜', 'Veg', 4.7, FALSE, TRUE, TRUE, NULL),
('House Special Foo Yung', '招牌芙蓉', 'Foo Yung', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn & Chicken Foo Yung', '虾鸡芙蓉', 'Foo Yung', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn Foo Yung', '芙蓉大虾', 'Foo Yung', 6, FALSE, TRUE, TRUE, NULL),
('Shrimp Foo Yung', '芙蓉虾仔', 'Foo Yung', 5.4, FALSE, TRUE, TRUE, NULL),
('Chicken Foo Yung', '芙蓉鸡', 'Foo Yung', 5.4, FALSE, TRUE, TRUE, NULL),
('Roast Pork Foo Yung', '芙蓉叉', 'Foo Yung', 5.4, FALSE, TRUE, TRUE, NULL),
('Mushroom Foo Yung', '芙蓉毛菇', 'Foo Yung', 5.4, FALSE, TRUE, TRUE, NULL),
('Chicken with Mushroom Foo Yung', '芙蓉毛鸡', 'Foo Yung', 5.4, FALSE, TRUE, TRUE, NULL),
('Sweet & Sour Mixed Balls', '古什球', 'Sweet & Sour', 6, FALSE, TRUE, TRUE, NULL),
('Sweet & Sour King Prawn Balls', '古虾球', 'Sweet & Sour', 6, FALSE, TRUE, TRUE, NULL),
('Sweet & Sour Chicken Balls', '古鸡球', 'Sweet & Sour', 5.5, FALSE, TRUE, TRUE, NULL),
('Sweet & Sour Pork Balls', '古鸡球', 'Sweet & Sour', 5.5, FALSE, TRUE, TRUE, NULL),
('Sweet & Sour Special in HK Style', '港特古老', 'Sweet & Sour', 6, FALSE, TRUE, TRUE, NULL),
('Sweet & Sour King Prawn in HK Style', '港古虾', 'Sweet & Sour', 6, FALSE, TRUE, TRUE, NULL),
('Sweet & Sour Chicken in HK Style', '港古鸡', 'Sweet & Sour', 5.5, FALSE, TRUE, TRUE, NULL),
('Sweet & Sour Pork in HK Style', '港古肉', 'Sweet & Sour', 5.5, FALSE, TRUE, TRUE, NULL),
('House Special Chop Suey', '招牌什水', 'Chop Suey', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn & Chicken Chop Suey', '什水虾鸡', 'Chop Suey', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn Chop Suey', '什水大虾', 'Chop Suey', 6, FALSE, TRUE, TRUE, NULL),
('Shrimp Chop Suey', '什水虾仔', 'Chop Suey', 5.4, FALSE, TRUE, TRUE, NULL),
('Chicken Chop Suey', '什水鸡', 'Chop Suey', 5.4, FALSE, TRUE, TRUE, NULL),
('Beef Chop Suey', '什水牛', 'Chop Suey', 5.4, FALSE, TRUE, TRUE, NULL),
('Roast Pork Chop Suey', '什水叉', 'Chop Suey', 5.4, FALSE, TRUE, TRUE, NULL),
('Crispy Beef with Ginger & Spring Onion', '姜葱牛', 'Deep Fried', 5.8, FALSE, TRUE, TRUE, NULL),
('Crispy Beef in Satay Sauce', '沙爹牛', 'Deep Fried', 5.8, FALSE, TRUE, TRUE, NULL),
('Crispy Beef in Kung Po Sauce', '宫保牛', 'Deep Fried', 5.8, FALSE, TRUE, TRUE, NULL),
('Crispy Beef in Peking Sauce', '京汁牛', 'Deep Fried', 5.8, FALSE, TRUE, TRUE, NULL),
('Crispy Beef in Black Bean Sauce', '士汁牛', 'Deep Fried', 5.8, FALSE, TRUE, TRUE, NULL),
('Crispy Beef with Salt & Pepper', '召盐牛', 'Deep Fried', 5.8, FALSE, TRUE, TRUE, NULL),
('Crispy Chicken with Salt & Pepper', '召盐鸡', 'Deep Fried', 5.8, FALSE, TRUE, TRUE, NULL),
('Crispy Chicken in Peking Sauce', '京汁鸡翅', 'Deep Fried', 5.8, FALSE, TRUE, TRUE, NULL),
('Deep Fries crisp beef cantonese', '牛丝广东', 'Deep Fried', 5.8, FALSE, FALSE, FALSE, NULL),
('Crisp chicken Cantonese', '鸡丝', 'Deep Fried', 5.8, FALSE, FALSE, FALSE, NULL),
('King Prawn in Batter Chips', '炸大虾条', 'English', 6, FALSE, FALSE, FALSE, NULL),
('Sirlion Steak Chips', '牛扒条', 'English', 7.6, FALSE, FALSE, FALSE, NULL),
('Mixed Grill Steak Chips', '什会牛扒条', 'English', 7.6, FALSE, FALSE, FALSE, NULL),
('Mixed Grill Chicken Chips', '什会鸡扒条', 'English', 7.6, FALSE, FALSE, FALSE, NULL),
('Roast Spring Chicken Chips', '烧鸡条', 'English', 4.8, FALSE, FALSE, FALSE, NULL),
('Grilled Liver Chips', '煎肝条', 'English', 4.8, FALSE, FALSE, FALSE, NULL),
('Grilled Sausage Chips', '煎肠条', 'English', 4.5, FALSE, FALSE, FALSE, NULL),
('King Prawn & Chicken Omelette Chips', '庵列虾鸡条', 'English', 6, FALSE, FALSE, FALSE, NULL),
('King Prawn Omelette Chips', '庵列虾条', 'English', 6, FALSE, FALSE, FALSE, NULL),
('Shrimp Omelette Chips', '庵列虾仔条', 'English', 5.5, FALSE, FALSE, FALSE, NULL),
('Chicken Omelette Chips', '庵列鸡条', 'English', 5.2, FALSE, FALSE, FALSE, NULL),
('Spanish Omelette Chips', '西班牙庵列条', 'English', 5.8, FALSE, FALSE, FALSE, NULL),
('Mushroom Omelette Chips', '毛菇庵列条', 'English', 4.8, FALSE, FALSE, FALSE, NULL),
('Roast Duck with Chinese Mushroom', '冬菇鸭', 'C Mushrm GP', 6.5, FALSE, TRUE, TRUE, NULL),
('King Prawn & Chicken with Chinese Mushroom', '冬菇虾鸡', 'C Mushrm GP', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn & Beef with Chinese Mushroom', '冬菇虾牛', 'C Mushrm GP', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with Chinese Mushroom', '冬菇大虾', 'C Mushrm GP', 6, FALSE, TRUE, TRUE, NULL),
('Beef with Chinese Mushroom', '冬菇牛', 'C Mushrm GP', 5.5, FALSE, TRUE, TRUE, NULL),
('Roast Pork with Chinese Mushroom', '冬菇叉', 'C Mushrm GP', 5.5, FALSE, TRUE, TRUE, NULL),
('House Special with GP in Chilli Sauce', '招牌青椒', 'C Mushrm GP', 6, FALSE, TRUE, TRUE, NULL),
('King Prawn with GP in Chilli Sauce', '青椒大虾', 'C Mushrm GP', 6, FALSE, TRUE, TRUE, NULL),
('Chicken with GP in Chilli Sauce', '青椒鸡', 'C Mushrm GP', 5.5, FALSE, TRUE, TRUE, NULL),
('Beef with GP in Chilli Sauce', '青椒牛', 'C Mushrm GP', 5.5, FALSE, TRUE, TRUE, NULL),
('Roast Pork in Chilli Sauce', '青椒叉', 'C Mushrm GP', 5.5, FALSE, TRUE, TRUE, NULL),
('BBQ Sauce', 'BBQ汁', 'Extra', 1.2, FALSE, FALSE, FALSE, NULL),
('OK Sauce', 'OK汁', 'Extra', 1.2, FALSE, FALSE, FALSE, NULL),
('Sweet & Sour Sauce', '古汁', 'Extra', 1.2, FALSE, FALSE, FALSE, NULL),
('Curry Sauce', '咖喱汁', 'Extra', 1.2, FALSE, FALSE, FALSE, NULL),
('Gravy', '芡汁', 'Extra', 1.2, FALSE, FALSE, FALSE, NULL),
('Prawn Crackers', '虾片', 'Extra', 1.7, FALSE, FALSE, FALSE, NULL),
('Soft Noodle', '炒面', 'Extra', 3, FALSE, FALSE, FALSE, NULL),
('Egg Fried Rice', '旦饭', 'Extra', 2, FALSE, FALSE, FALSE, NULL),
('Boiled Rice', '白饭', 'Extra', 1.8, FALSE, FALSE, FALSE, NULL),
('Mixed Vegetables', '什才', 'Extra', 2.7, FALSE, FALSE, FALSE, NULL),
('Bamboo Shoots & Water Chestnuts', '竹马', 'Extra', 2.6, FALSE, FALSE, FALSE, NULL),
('Bean Sprouts', '芽菜', 'Extra', 2.5, FALSE, FALSE, FALSE, NULL),
('Cashew Nuts', '腰果', 'Extra', 2.5, FALSE, FALSE, FALSE, NULL),
('Mushroom', '毛菇', 'Extra', 2.2, FALSE, FALSE, FALSE, NULL),
('Onion', '洋葱', 'Extra', 2.2, FALSE, FALSE, FALSE, NULL),
('Chips with Curry', '咖喱薯条', 'Extra', 2.2, FALSE, FALSE, FALSE, NULL),
('Chips with Gravy', '芡汁薯条', 'Extra', 2.2, FALSE, FALSE, FALSE, NULL),
('Chips with Sweet & Sour Sauce', '古汁薯条', 'Extra', 2.2, FALSE, FALSE, FALSE, NULL),
('Chips & Fried Rice with Curry', '咖喱条饭', 'Extra', 3.2, FALSE, FALSE, FALSE, NULL),
('Chips & Fried Rice with Gravy', '芡汁条饭', 'Extra', 3.2, FALSE, FALSE, FALSE, NULL),
('Chips & Fried Rice with Sweet & Sour Sauce', '古汁条饭', 'Extra', 3.2, FALSE, FALSE, FALSE, NULL),
('Chips & Mushroom with Gravy', '芡汁毛菇条', 'Extra', 3.2, FALSE, FALSE, FALSE, NULL),
('Chips', '薯条', 'Extra', 1.2, FALSE, FALSE, FALSE, NULL),
('Boiled Rice', '白反', 'Others', 0, FALSE, FALSE, FALSE, NULL),
('Chip', '条', 'Others', 0, FALSE, FALSE, FALSE, NULL),
('Fried Rice', '炒反', 'Others', 0.3, FALSE, FALSE, FALSE, NULL),
('Chow Mein', '炒面', 'Others', 0.5, FALSE, FALSE, FALSE, NULL),
('Cant Spring Rolls(4)', '广春卷(4)', 'Others', 2.6, FALSE, FALSE, FALSE, NULL),
('Cant Spring Rolls(6)', '广春卷(6)', 'Others', 3.2, FALSE, FALSE, FALSE, NULL),
('Cant Spring Rolls(8)', '广春卷(8)', 'Others', 3.5, FALSE, FALSE, FALSE, NULL),
('A For 1 Person', 'A一人餐', 'Set Dinner', 8.5, FALSE, TRUE, FALSE, '201,191,243'),
('B For 2 Persons', 'B二人餐', 'Set Dinner', 19, FALSE, TRUE, FALSE, '304,125,128,192,61'),
('C For 3 Persons', 'C三人餐', 'Set Dinner', 28, FALSE, TRUE, FALSE, '305,190,117,137,37a,61'),
('D For 4 Persons', 'D四人餐', 'Set Dinner', 36, FALSE, TRUE, FALSE, '14,306,108,189,117,36a,61'),
('Peking Feast (For 2 Persons)', '京2人餐', 'Set Dinner', 20, FALSE, TRUE, FALSE, '10,7,18,100,126,61'),
('Shang Hai Feast (For 3 Persons)', '上海3人餐', 'Set Dinner', 35, FALSE, TRUE, FALSE, '13,2,7,14,56,195,61'),
('Canton Feast (For 4 Persons)', '广4人餐', 'Set Dinner', 46, FALSE, TRUE, FALSE, '10,3h,7,15,193,165,117,61'),
('Chicken Fried Rice', '鸡饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Curried Chicken with Fried Rice', '咖喱鸡饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Curried Beef with Fried Rice', '咖喱牛饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Curried Mushroom with Fried Rice', '咖喱毛菇饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Chicken Foo Yung with Fried Rice', '芙蓉鸡饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Roast Pork Foo Yung with Fried Rice', '芙蓉叉烧饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Mushroom Foo Yung with Fried Rice', '毛菇芙蓉饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Chicken & Mushroom with Fried Rice', '毛菇鸡饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Beef & Mushroom with Fried Rice', '毛菇牛饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Sweet & Sour Chicken with Fried Rice', '古鸡饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Sweet & Sour Pork with Fried Rice', '古猪饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Roast Pork Fried Rice', '叉烧饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Chicken Omelette with Chips', '鸡庵列条', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Mushroom Omelette with Chips', '毛菇庵列条', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Chicken Chow Mein', '鸡面', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Beef Chow Mein', '牛面', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Roast Pork Chow Mein', '叉烧面', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Shrimp Chop Suey with Fried Rice', '虾仔什水饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Chicken Chop Suey with Fried Rice', '什水鸡饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Beef Chop Suey with Fried Rice', '什水牛饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL),
('Curried Shrimp with Fried Rice', '咖喱虾仔饭', 'Lunch', 4, FALSE, FALSE, FALSE, NULL)